# Generated by Django 4.1 on 2023-05-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotelapp", "0002_auto_20220321_2039"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accommodation",
            options={"verbose_name": "客房订单管理", "verbose_name_plural": "客房订单管理"},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "顾客管理", "verbose_name_plural": "顾客管理"},
        ),
        migrations.AlterModelOptions(
            name="food",
            options={"verbose_name": "餐厅管理", "verbose_name_plural": "餐厅管理"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "餐厅订单管理", "verbose_name_plural": "餐厅订单管理"},
        ),
        migrations.AlterModelOptions(
            name="park",
            options={"verbose_name": "停车场管理", "verbose_name_plural": "停车场管理"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "客房信息管理", "verbose_name_plural": "客房信息管理"},
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={"verbose_name": "员工信息管理", "verbose_name_plural": "员工信息管理"},
        ),
        migrations.AlterModelOptions(
            name="vip",
            options={"verbose_name": "会员信息管理", "verbose_name_plural": "会员信息管理"},
        ),
    ]
