# Generated by Django 4.1 on 2023-06-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotelapp", "0003_alter_accommodation_options_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="顾客相片",
            field=models.ImageField(blank=True, null=True, upload_to="Client_images/"),
        ),
        migrations.AddField(
            model_name="food",
            name="菜品相片",
            field=models.ImageField(blank=True, null=True, upload_to="Client_images/"),
        ),
        migrations.AddField(
            model_name="room",
            name="客房款式相片",
            field=models.ImageField(blank=True, null=True, upload_to="Client_images/"),
        ),
        migrations.AddField(
            model_name="staff",
            name="员工相片",
            field=models.ImageField(blank=True, null=True, upload_to="Client_images/"),
        ),
        migrations.AddField(
            model_name="vip",
            name="会员相片",
            field=models.ImageField(blank=True, null=True, upload_to="Client_images/"),
        ),
    ]
